# Generated by Django 2.2.6 on 2019-12-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0003_auto_20191128_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penetrationtestticketsubworkflow',
            name='penetration_test_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='vulmannager.PenetrationTestTicket'),
        ),
    ]
