# Generated by Django 2.2.6 on 2019-12-02 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0004_auto_20191202_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penetrationtestticket',
            name='ticket_result',
        ),
        migrations.AddField(
            model_name='penetrationtestticketresult',
            name='penetration_test_ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_result', to='vulmannager.PenetrationTestTicket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penetrationtestticketsubworkflow',
            name='penetration_test_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_workflow', to='vulmannager.PenetrationTestTicket'),
        ),
    ]
