# Generated by Django 2.2.6 on 2019-12-02 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0005_auto_20191202_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='penetrationtestticketsubworkflow',
            name='action',
            field=models.BooleanField(verbose_name='操作'),
            preserve_default=False,
        ),
    ]
