# Generated by Django 2.2.6 on 2019-12-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0007_auto_20191202_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penetrationtestticketsubworkflow',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
