# Generated by Django 2.2.6 on 2019-12-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0008_auto_20191203_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulworkflow',
            name='vulnerability',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='vul_work_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='vulmannager.VulWorkflow'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='vul_type',
            field=models.CharField(choices=[('File Inclusion', '文件包含'), ('UXSS', 'UXSS通用跨站脚本'), ('XSS', 'XSS跨站脚本'), ('File Upload', '文件上传'), ('Weak Password', '弱口令'), ('Command Execution', '命令执行'), ('Code Execution', '代码执行'), ('Unauthorized access', '未授权&越权'), ('SQL Injection', 'SQL注入'), ('SSRF', 'SSRF服务器端请求伪造'), ('Arbitrary File Download', '任意文件下载'), ('Arbitrary File Read', '任意文件读取'), ('Arbitrary File Deletion', '任意文件删除'), ('Information Disclosure', '敏感信息泄漏'), ('XML Injection', 'XXE外部实体注入'), ('Unknown', '未知类型')], max_length=30, verbose_name='漏洞类型'),
        ),
    ]
