# Generated by Django 2.2.6 on 2019-12-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0009_auto_20191213_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerability',
            old_name='vul_work_flow',
            new_name='vul_workflow',
        ),
    ]
