# Generated by Django 2.2.6 on 2019-12-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0010_auto_20191213_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='vul_workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='vulmannager.VulWorkflow'),
        ),
    ]
