# Generated by Django 2.2.6 on 2019-12-16 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vulmannager', '0011_auto_20191213_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulworkflow',
            name='transactor',
            field=models.ManyToManyField(related_name='vul_transactor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='vul_workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability', to='vulmannager.VulWorkflow'),
        ),
        migrations.AlterField(
            model_name='vulsubworkflow',
            name='transactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_vul_transactor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vulsubworkflow',
            name='vul_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_workflow', to='vulmannager.VulWorkflow'),
        ),
    ]
