# Generated by Django 2.2.6 on 2019-12-16 06:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0015_vulnerability_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulworkflow',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vul_work_flows', to='vulmannager.Asset'),
            preserve_default=False,
        ),
    ]
