# Generated by Django 2.2.6 on 2019-12-16 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0017_remove_vulnerability_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='pics',
            field=models.ManyToManyField(related_name='pics', to=settings.AUTH_USER_MODEL),
        ),
    ]
