# Generated by Django 2.2.6 on 2019-12-17 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0020_auto_20191217_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='pics',
            field=models.ManyToManyField(blank=True, related_name='pics', to=settings.AUTH_USER_MODEL),
        ),
    ]
