# Generated by Django 2.2.6 on 2019-12-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0023_auto_20191217_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='vulmannager.Asset'),
        ),
    ]
