# Generated by Django 2.2.6 on 2019-12-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulmannager', '0024_auto_20191218_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='vulmannager.Asset'),
        ),
    ]
