# Generated by Django 2.2.6 on 2019-12-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=256, verbose_name='服务地址')),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=128, verbose_name='邮箱账号')),
                ('password', models.CharField(max_length=128, verbose_name='邮箱密码')),
                ('encryption_method', models.CharField(choices=[('不加密', 'NONE'), ('SSL加密', 'SSL'), ('TLS加密', 'TLS')], max_length=8, verbose_name='加密方式')),
                ('signature', models.TextField(blank=True, verbose_name='邮件签名')),
            ],
        ),
    ]
